# Generated by Django 4.2.2 on 2023-06-24 10:15

from django.db import migrations, models
import fruitipedia_app.fruitipedia.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[fruitipedia_app.fruitipedia.validators.min_name_length_validator, fruitipedia_app.fruitipedia.validators.validate_name_letters])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
