# Generated by Django 3.2.18 on 2023-03-07 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Username must have at least 2 characters!'), django.core.validators.RegexValidator(code='invalid_username', message='Plant name should contain only letters!', regex='^([A-Za-z]+)+$')])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Username must have at least 2 characters!')])),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Your name must start with a capital letter and consists of only letters!', regex='^([A-Z][a-z]+)$')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Your name must start with a capital letter and consists of only letters!', regex='^([A-Z][a-z]+)$')])),
                ('profile_picture', models.URLField(blank=True)),
            ],
        ),
    ]
